removes reference `installer.remove_untracked`
python-poetry/poetry-bundle-plugin pull request #1
Opened 2021-08-03 23:53 UTC by jtzero

the function has been moved to Solver

fixes error 
```

  AttributeError

  'Installer' object has no attribute 'remove_untracked'

  at ~/.asdf/installs/python/3.8.5/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/poetry_bundle_plugin/bundlers/venv_bundler.py:133 in bundle
      129│             poetry.locker,
      130│             poetry.pool,
      131│             poetry.config,
      132│         )
    → 133│         installer.remove_untracked()
      134│         installer.use_executor(poetry.config.get("experimental.new-installer", False))
      135│
      136│         return_code = installer.run()
      137│         if return_code:
```

2021-10-20 10:31 UTC, MaciejKucia commented
@sdispater Can this fix be merged? Thanks.
As an alternative what would be the compatible poetry version?

2021-10-31 16:08 UTC, talhajunaidd commented
I'm also facing the same issue, can we please merge the fix?

2021-11-04 21:06 UTC, jwillikers commented
Same issue.

2021-12-13 12:49 UTC, talhajunaidd commented
any update?

2022-01-17 14:32 UTC, mgb-ingenuity commented
What's the status on this?

2022-01-20 14:13 UTC, RockyMM commented
Just to add -> same issue. Any chance for a merge?

2022-01-21 14:37 UTC, mgb-ingenuity commented
BUMP

2022-01-23 18:49 UTC, neersighted requested changes

2022-01-23 18:49 UTC, neersighted commented on src/poetry_bundle_plugin/bundlers/venv_bundler.py
> +        installer.requires_synchronization(True)
There should be no need to explicitly pass the default argument here. Otherwise, LGTM.

2022-04-07 02:48 UTC, branchvincent approved these changes
thanks @jtzero, and sorry for the long delay. I'll try to get this published asap

2022-04-07 02:50 UTC, merged